using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.InvoiceJobCostItems
{
    [Table("dbo", "InvoiceJobCostItem", "qci")]
    public class InvoiceJobCostItemBasicPoco : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        public int InvoiceId { get; set; }

        public int JobCostItemId { get; set; }

        public string ShortDescription { get; set; }

        public string LongDescription { get; set; }

        public decimal UnitCost { get; set; }

        public decimal UnitPrice { get; set; }

        public decimal TotalPrice { get; set; }

        public decimal Quantity { get; set; }

        public bool IsBillable { get; set; }

        [AutoGenerated]
        public byte[] Version { get; set; }
    }
}
