CREATE TABLE [dbo].[Credential]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Email] VARCHAR(200) NOT NULL,
    [Password] VARCHAR(50) NULL,
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[UtcCreated] DATETIME2(0) NOT NULL DEFAULT(GETUTCDATE()),
	[UtcUpdated] DATETIME2(0) NOT NULL DEFAULT(GETUTCDATE())
)
