CREATE TABLE [dbo].[Credential]
(
    [Id] INT NOT NULL IDENTITY,
    [Email] VARCHAR(200) NOT NULL,
    [Password] VARCHAR(50) NOT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT(0),
    [Version] ROWVERSION NOT NULL,
	[UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[UtcUpdated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
    CONSTRAINT [PK_dbo_Credential_Id] PRIMARY KEY CLUSTERED (Id ASC)
)
