CREATE TABLE [dbo].[Customer]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[OtherName] NVARCHAR(50) NOT NULL,
	[MobilePhone] VARCHAR(50) NULL,
	[Dob] DATE NULL,
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[CreatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	[UpdatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE())
)
