CREATE TABLE [dbo].[CustomerType]
(
    [Id] INT NOT NULL IDENTITY,
    [OrganizationId] INT NOT NULL,
    [Description] NVARCHAR(50) NOT NULL,
    [NameDisplayStrategy] VARCHAR(50) NULL,
	[UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[UtcUpdated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT [PK_dbo_CustomerType] PRIMARY KEY CLUSTERED (Id ASC)
)
