CREATE TABLE [dbo].[JobTimesheet]
(
	[Id] INT NOT NULL IDENTITY,
	[OrganizationId] INT NOT NULL,
	[JobId] INT NOT NULL,
	[JobTimesheetTypeId] INT NOT NULL,
	[LastChangeOrganizationUserId] INT NULL,
	[JobTaskId] INT NOT NULL,
	[IsWriteOff] BIT NOT NULL DEFAULT(0),
	[StaffId] INT NOT NULL,
	[StartDateTime] DATETIME2(0) NULL,
	[EndDateTime] DATETIME2(0) NULL,
	[OriginalMinutes] INT NULL,
	[RoundedMinutes] INT NULL,
	[ShortDescription] NVARCHAR (100) NULL,
	[LongDescription] NVARCHAR (2000) NULL,
	[IsBillable] BIT NOT NULL DEFAULT(0),
	[BaseRate] DECIMAL(10,3) NOT NULL DEFAULT(0),
	[BillableRate] DECIMAL(10,3) NOT NULL DEFAULT(0),
	[IsDuration] BIT NOT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT(0),
	[Version] ROWVERSION NOT NULL,
	[UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[UtcUpdated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CONSTRAINT [PK_dbo_JobTimesheet_Id] PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT [FK_dbo_JobTimesheet_dbo_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organization]([Id]),
	CONSTRAINT [FK_dbo_JobTimesheet_dbo_Job] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job]([Id]),
	CONSTRAINT [FK_dbo_JobTimesheet_dbo_JobTask] FOREIGN KEY ([JobTaskId]) REFERENCES [dbo].[JobTask]([Id]),
	CONSTRAINT [FK_dbo_JobTimesheet_dbo_Staff] FOREIGN KEY ([StaffId]) REFERENCES [dbo].[Staff]([Id]),
	CONSTRAINT [FK_dbo_JobTimesheet_dbo_OrganizationUser] FOREIGN KEY ([LastChangeOrganizationUserId]) REFERENCES [dbo].[OrganizationUser]([Id])
)
