CREATE TABLE [dbo].[Organization]
(
    [Id] INT NOT NULL IDENTITY,
    [CountryId] INT NOT NULL,
    [Name] VARCHAR(50) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT(0),
    [DisplayName] VARCHAR(150) NULL,
    [Version] ROWVERSION NOT NULL,
    [UtcCreated] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [UtcUpdated] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
    CONSTRAINT [PK_dbo_Organization_Id] PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT [FK_Organization_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country]([Id])
)
