CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
    [ShopId] INT NOT NULL,
    [Description] VARCHAR(200) NULL, 
    [LongDescription] VARCHAR(MAX) NULL, 
    [IsDeleted] BIT NOT NULL DEFAULT(0),
    [IsActive] BIT NOT NULL DEFAULT(1),    
    [UtcCreatedOn] DATETIME2(0) NOT NULL DEFAULT GETUTCDATE(), 
    [UtcUpdatedOn] DATETIME2(0) NOT NULL DEFAULT GETUTCDATE(),
    [Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID())
)
