CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(150) NOT NULL,
    [Description] VARCHAR(MAX) NULL, 
    [UtcCreatedOn] DATETIME2(0) NOT NULL DEFAULT GETUTCDATE(), 
    [UtcUpdatedOn] DATETIME2(0) NOT NULL DEFAULT GETUTCDATE()
)
