CREATE TABLE [dbo].[Quote]
(
    [Id] INT NOT NULL IDENTITY,
    [OrganizationId] INT NOT NULL,
    [LastChangeOrganizationUserId] INT NULL,
    [QuoteStatusId] INT NOT NULL,
    [Name] NVARCHAR(200) NOT NULL,
    [JobId] INT NULL,
    [InvoiceId] INT NULL,
    [CustomerId] INT NOT NULL,
    [ContactId] INT NULL,
    [Code] VARCHAR(50) NOT NULL,
    [DueDate] DATETIME2(0) NULL,
    [IsFixedPrice] BIT NOT NULL DEFAULT(0),
    [TotalPrice] DECIMAL(10,3) DEFAULT(0),
    [TotalPriceWithTax] DECIMAL(10,3) DEFAULT(0),
    [ShortDescription] NVARCHAR(200) NOT NULL,
    [LongDescription] NVARCHAR(MAX) NULL,
    [Version] ROWVERSION NOT NULL,
	[UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[UtcUpdated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
    CONSTRAINT [PK_dbo_Quote_Id] PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT [FK_Quote_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organization]([Id]),
    CONSTRAINT [FK_Quote_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer]([Id]),
    CONSTRAINT [FK_Quote_Contact] FOREIGN KEY ([ContactId]) REFERENCES [dbo].[Contact]([Id]),
    CONSTRAINT [FK_dbo_Quote_dbo_QuoteStatus] FOREIGN KEY ([QuoteStatusId]) REFERENCES [dbo].[QuoteStatus]([Id]),
    CONSTRAINT [FK_dbo_Quote_dbo_OrganizationUser] FOREIGN KEY ([LastChangeOrganizationUserId]) REFERENCES [dbo].[OrganizationUser]([Id])
)
