CREATE TABLE [dbo].[QuoteType]
(
    [Id] INT NOT NULL,
    [Description] NVARCHAR(50) NOT NULL,
    [Version] ROWVERSION NOT NULL,
	[UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[UtcUpdated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT [PK_dbo_QuoteType_Id] PRIMARY KEY CLUSTERED (Id ASC),
)
