CREATE TABLE [dbo].[Staff]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [BranchId] INT NOT NULL,
    [FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[OtherName] NVARCHAR(50) NOT NULL,
    [MobilePhone] VARCHAR(50) NULL,
	[Dob] DATE NULL,
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[UtcCreatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	[UtcUpdatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
    CONSTRAINT [FK_Staff_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch]([Id]),
)
