CREATE TABLE [dbo].[Supplier]
(
    [Id] INT NOT NULL IDENTITY,
    [Version] ROWVERSION NOT NULL,
    [UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	[UtcUpdated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
    [Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
    CONSTRAINT [PK_dbo_Supplier_Id] PRIMARY KEY CLUSTERED (Id ASC),
)
