CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[BranchId] INT NOT NULL,
	[TableTypeId] INT NOT NULL,
	[Code] VARCHAR(150) NOT NULL,
	[NumberOfSeats] INT NOT NULL,
	[MaxNumberOfSeats] INT NULL,
    [Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[CreatedOn] DATETIME2(0) NOT NULL DEFAULT(GETUTCDATE()),
	[UpdatedOn] DATETIME2(0) NOT NULL DEFAULT(GETUTCDATE()),
	CONSTRAINT [FK_Table_TableType] FOREIGN KEY ([TableTypeId]) REFERENCES [dbo].[TableType] ([Id])
)
