using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.QuoteTasks
{
    [Table("dbo", "QuoteTask", "qt")]
    public class QuoteTaskBasicPoco : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        public int QuoteId { get; set; }

        public int TaskDefinitionId { get; set; }

        public int? DisplayOrder { get; set; }

        public int EstimatedTimeInMinutes { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? EndDate { get; set; }

        public DateTime? CompletedDate { get; set; }

        public bool IsBillable { get; set; }

        public bool IsCompleted { get; set; }

        public string ShortDescription { get; set; }

        [AutoGenerated]
        public byte[] Version { get; set; }

        [AutoGenerated]
        public Guid Uid { get; set; }
    }
}
