CREATE TABLE [apiv1].[OAuthClient]
(
	[Id] INT NOT NULL IDENTITY,
	[ClientId] VARCHAR(50) NOT NULL,
	[ClientSecret] VARCHAR(400) NOT NULL,
	[Name] NVARCHAR(100),
	[IsInternal] BIT NOT NULL DEFAULT(0),
	[Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[Version] ROWVERSION NOT NULL,
	[UtcCreated] DATETIME2(3) NOT NULL DEFAULT(SYSUTCDATETIME()),
	CONSTRAINT [PK_OAuthClient_Id] PRIMARY KEY CLUSTERED ([Id] ASC), -- WITH (DATA_COMPRESSION = PAGE),
	CONSTRAINT [UQ_OAuthClient_Uid] UNIQUE NONCLUSTERED ([Uid] ASC), -- WITH (DATA_COMPRESSION = PAGE)
)
