using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    [Table("dbo", "Credential", "c")]
    public class Credential
    {
        [Primary]
        public int Id { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public bool IsDeleted { get; set; }

        [AutoGenerated, IgnoreWhenUpdate]
        public byte[] Version { get; set; }

        [AutoGenerated, IgnoreWhenUpdate]
        public DateTime UtcCreated { get; set; }

        [AutoGenerated]
        public DateTime UtcUpdated { get; set; }

        [AutoGenerated, IgnoreWhenUpdate]
        public Guid Uid { get; set; }
    }
}
