using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    [Table("dbo", "Customer", "c")]
    public class Customer : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        [IgnoreMappingWhenUpdate]
        public int OrganizationId { get; set; }

        public int? CustomerTypeId { get; set; }

        public string Code { get; set; }

        public string Phone { get; set; }

        public string Email { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string OtherName { get; set; }

        public string MobilePhone { get; set; }

        public int? UpdatedByStaffId { get; set; }

        [IgnoreMappingWhenUpdate]
        public string Version { get; set; }

        public DateTime? Dob { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public Guid Uid { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public DateTime UtcCreated { get; set; }

        [AutoGenerated]
        public DateTime UtcUpdated { get; set; }
    }
}
