using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    [Table("dbo", "Customer", "c")]
    public class Customer : IDataEntity, ITrackUpdateTime
    {
        [Primary]
        public int Id { get; set; }

        [IgnoreWhenUpdate]
        public int OrganizationId { get; set; }

        public int CustomerTypeId { get; set; }

        public bool IsProspect { get; set; }

        public string Gender { get; set; }

        [SearchableAsEnglish]
        public string Code { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string OtherName { get; set; }

        public string Phone { get; set; }

        public string MobilePhone { get; set; }

        [SearchableAsEnglish]
        public string Email { get; set; }

        public DateTime? Dob { get; set; }

        public bool IsDeleted { get; set; }

        public int? InvoiceCustomerId { get; set; }

        [AutoGenerated]
        public byte[] Version { get; set; }

        [AutoGenerated]
        public Guid Uid { get; set; }

        [AutoGenerated]
        public DateTime UtcCreated { get; set; }

        [AutoGenerated]
        public DateTime UtcUpdated { get; set; }

        [Computed, SearchableAsUnicode]
        public string SearchName { get; set; }
    }
}
