using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    public class Job : IDataEntity, IChangeByTimeTracking
    {
        [Primary]
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int JobStatusId { get; set; }
        public string Code { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public int CustomerId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime? DueDate { get; set; }
        public int? UpdatedByStaffId { get; set; }
        [IgnoreMappingWhenUpdate]
        public byte[] Version { get; set; }
        public DateTime UtcCreated { get; set; }
        public DateTime UtcUpdated { get; set; }
        public string Uid { get; set; }
    }

    public interface IChangeByTimeTracking
    {
        [AutoGenerated, IgnoreMappingWhenUpdate]
        DateTime UtcCreated { get; set; }

        [AutoGenerated]
        DateTime UtcUpdated { get; set; }
    }
}
