using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    [Table("dbo", "JobTimesheet", "jts")]
    public class JobTimesheet : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        public int JobTimesheetTypeId { get; set; }

        public int? JobTaskId { get; set; }

        public int StaffId { get; set; }

        public DateTime? StartDateTime { get; set; }

        public DateTime? EndDateTime { get; set; }

        public int OriginalMinutes { get; set; }

        public int RoundedMinutes { get; set; }

        public string ShortDescription { get; set; }

        public string LongDescription { get; set; }

        public bool IsBillable { get; set; }

        public bool IsDuration { get; set; }

        public bool IsWriteOff { get; set; }

        public decimal BaseRate { get; set; }

        public decimal BillableRate { get; set; }

        [AutoGenerated]
        public byte[] Version { get; set; }

        [AutoGenerated]
        public DateTime UtcCreated { get; set; }

        [AutoGenerated]
        public DateTime UtcUpdated { get; set; }

        [AutoGenerated]
        public Guid Uid { get; set; }
    }
}
