using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    [Table("apiv1","OAuthClient", "oauthclient")]
    public class OAuthClient
    {
        [Primary]
        public int Id { get; set; }

        public string ClientId { get; set; }

        public string ClientSecret { get; set; }

        public string Name { get; set; }

        public bool IsInternal { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public byte[] Version { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public Guid Uid { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public DateTime UtcCreated { get; set; }
    }
}
