using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.DataEntities
{
    [Table("dbo", "Quote", "q")]
    public class Quote : IDataEntity
    {
        [Primary]
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int? LastChangeOrganizationUserId { get; set; }
        public int QuoteStatusId { get; set; }
        public string Name { get; set; }
        public int? JobId { get; set; }
        public int CustomerId { get; set; }
        public int? ContactId { get; set; }
        public string Code { get; set; }
        public DateTime? DueDate { get; set; }
        public bool IsFixedPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalPriceWithTax { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        [AutoGenerated]
        public byte[] Version { get; set; }
        [AutoGenerated]
        public DateTime UtcCreated { get; set; }
        [AutoGenerated]
        public DateTime UtcUpdated { get; set; }
        [AutoGenerated]
        public Guid Uid { get; set; }

    }
}
