using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.QuoteCostItems
{
    [Table("dbo", "QuoteCostItem", "qci")]
    public class QuoteCostItemBasicPoco : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        public int QuoteId { get; set; }

        public int CostItemId { get; set; }

        public string ShortDescription { get; set; }

        public decimal UnitCost { get; set; }

        public decimal UnitPrice { get; set; }

        public decimal TotalPrice { get; set; }

        public decimal Quantity { get; set; }

        public bool IsBillable { get; set; }

        [AutoGenerated]
        public byte[] Version { get; set; }
    }
}
