using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.TaskDefinitions
{
    [Table("dbo", "TaskDefinition", "td")]
    public class TaskDefinitionBasicPoco : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        public int OrganizationId { get; set; }

        public string ShortDescription { get; set; }

        public decimal BaseRate { get; set; }

        public decimal BillableRate { get; set; }

        public bool IsDeleted { get; set; }

        [AutoGenerated]
        public byte[] Version { get; set; }

        [AutoGenerated]
        public Guid Uid { get; set; }
    }
}
