using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.Quotes
{
    [Table("dbo", "Quote", "q")]
    public class QuoteBasicPoco : IDataEntity
    {
        [Primary]
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int QuoteStatusId { get; set; }
        public string Name { get; set; }
        public int? JobId { get; set; }
        public int CustomerId { get; set; }
        public int? ContactId { get; set; }
        public string Code { get; set; }
        public DateTime? DueDate { get; set; }
        public bool IsFixedPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public string ShortDescription { get; set; }
        [AutoGenerated]
        public byte[] Version { get; set; }
    }
}
