using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.Views
{
    [Table("dbo", "View_ValidCredential", "vvcrdn")]
    public class ValidCredential
    {
        [Primary]
        public int Id { get; set; }

        [IgnoreMappingWhenUpdate]
        public int OrganizationId { get; set; }

        [IgnoreMappingWhenUpdate]
        public int CredentialTypeId { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public bool IsDeleted { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public byte[] Version { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public DateTime UtcCreated { get; set; }

        [AutoGenerated]
        public DateTime UtcUpdated { get; set; }

        [AutoGenerated, IgnoreMappingWhenUpdate]
        public Guid Uid { get; set; }
    }
}
