using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.Views
{
    [Table("dbo", "View_ValidCredential", "vvcrdn")]
    public class ValidCredential
    {
        [Primary]
        public int Id { get; set; }

        [IgnoreWhenUpdate]
        public int OrganizationId { get; set; }

        [IgnoreWhenUpdate]
        public int OrganizationUserId { get; set; }

        [IgnoreWhenUpdate]
        public int OrganizationUserTypeId { get; set; }

        public string Email { get; set; }

        [IgnoreWhenRead]
        public string Password { get; set; }

        public bool IsDeleted { get; set; }

        [AutoGenerated, IgnoreWhenUpdate]
        public Guid Uid { get; set; }
    }
}
