using System;
using WaterPoint.Data.Entity.Attributes;

namespace WaterPoint.Data.Entity.Pocos.Views
{
    [Table("dbo", "View_ValidCredential", "vvcrdn")]
    public class ValidCredential : IDataEntity
    {
        [Primary]
        public int Id { get; set; }

        public int OrganizationId { get; set; }

        public int OrganizationUserId { get; set; }

        public int OrganizationUserTypeId { get; set; }

        public int EntityId { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public bool IsDeleted { get; set; }

        [AutoGenerated]
        public Guid Uid { get; set; }
    }
}
