CREATE TABLE [dbo].[DiningTable]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Code] VARCHAR(150) NOT NULL,
	[IsVip] BIT NOT NULL DEFAULT(0),
	[DiningTableGrouptId] INT NULL,
    [Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),	
	[CreatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	[UpdatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE())    
)
