CREATE TABLE [dbo].[Restaurant]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(150) NOT NULL,
	[PreferedName] NVARCHAR(150) NULL,
	[Phone] VARCHAR(50) NULL, 
    [Uid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[CreatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	[UpdatedOn] DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE())
)
