CREATE TABLE [dbo].[Supplier]
(
	[Id] INT NOT NULL IDENTITY, 
    [Name] NVARCHAR(150) NOT NULL, 
    [DisplayName] NVARCHAR(150) NULL, 
    [Mobile] NVARCHAR(100) NULL, 
    [Phone1] NVARCHAR(100) NULL, 
    [Uid] UNIQUEIDENTIFIER DEFAULT(NEWID()), 
    CONSTRAINT [PK_Supplier] PRIMARY KEY ([Id]) 
)
